### ISSUE TITLE
Any chance on an update?

### ISSUE THREAD

**Issue by IrishBruse** [chances/wren-sharp#3]
I cant get anything working it fails all the tests im using the latest dll so that might be it
all test return this which is weird cause the c++ file has these defined 
System.EntryPointNotFoundException : Unable to find an entry point named 'wrenInitConfiguration' in DLL 'wren.dll'.

**Comment by chances** [comment]
@IrishBruse Were you able to resolve the issue?

This library is built against a [specific commit in wren's repo](https://github.com/wren-lang/wren/tree/53cf6f511bf9184966d280fbea139470df382190) (some commit inbetween wren 0.2 and 0.3, it seems) and the existing tests expect that version. I haven't updated the library from an apparent lack of interest, but your issue changes that. 😉️

Say the word, I'll set aside some time to update the library for wren's latest release.
